---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: default_pear
    run_list:
      - recipe[phpmd::default]
    attributes:
      pdepend:
        install_method: pear
  - name: default_composer
    run_list:
      - recipe[phpmd::default]
    attributes:
      pdepend:
        install_method: composer
  - name: default_phar
    run_list:
      - recipe[phpmd::default]
    attributes:
      pdepend:
        install_method: phar
