---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04-chef-12
    run_list:
      - recipe[apt]
    driver:
      box: bento/ubuntu-14.04
    provisioner:
      require_chef_omnibus: 12
  - name: ubuntu-14.04-chef-13
    run_list:
      - recipe[apt]
    driver:
      box: bento/ubuntu-14.04
    provisioner:
      require_chef_omnibus: 13
  - name: ubuntu-16.04-chef-12
    run_list:
      - recipe[apt]
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12
  - name: ubuntu-16.04-chef-13
    run_list:
      - recipe[apt]
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 13
  - name: centos-7.3-chef-12
    driver:
      box: bento/centos-7.3
    provisioner:
      require_chef_omnibus: 12
  - name: centos-7.3-chef-13
    driver:
      box: bento/centos-7.3
    provisioner:
      require_chef_omnibus: 13

suites:
  - name: default_pear
    run_list:
      - recipe[phpmd::default]
    attributes:
      pdepend:
        install_method: pear
  - name: default_composer
    run_list:
      - recipe[phpmd::default]
    attributes:
      pdepend:
        install_method: composer
  - name: default_phar
    run_list:
      - recipe[phpmd::default]
    attributes:
      pdepend:
        install_method: phar
