---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[phpmd::default]
  - name: pear
    run_list:
      - recipe[phpmd::default]
    attributes:
      pdepend:
        install_method: pear
  - name: composer
    run_list:
      - recipe[phpmd::default]
    attributes:
      pdepend:
        install_method: composer
  - name: phar
    run_list:
      - recipe[phpmd::default]
    attributes:
      pdepend:
        install_method: phar
